web:
  image: 'gitlab/gitlab-ce:${GITLAB_IMAGE_TAG}'
  restart: always
  hostname: '${GITLAB_SUBDOMAIN}.${GITLAB_DOMAIN}'
  # environment:
    # GITLAB_OMNIBUS_CONFIG: |
        # any config added here will override whatever's in the gitlab.rb file, if one exists.
        # more information: https://docs.gitlab.com/omnibus/docker/#pre-configure-docker-container
  ports:
    - '${HOST_HTTP}:80'
    - '${HOST_HTTPS}:443'
    - '${HOST_SSH}:22' # git interacts ssh by default, this is always a bit of a pain to deal with.
  volumes:
    - '${HOST_CONFIG_PATH}:/etc/gitlab'
    - '${HOST_LOG_PATH}:/var/log/gitlab'
    - '${HOST_DATA_PATH}:/var/opt/gitlab'
runner:
  image: gitlab/gitlab-runner:${RNR_IMAGE_TAG}
  restart: always
  links:
    - web
  environment:
    REGISTER_NON_INTERACTIVE: "true"
    RUNNER_NAME: gitlab-runner-master
    CI_SERVER_URL: http://web                     # we link with the web container, so that's it's name here
    TAG_LIST: alpine,master
    RUN_UNTAGGED: "false"
    RUNNER_EXECUTOR: "shell"
    REGISTRATION_TOKEN: yxi6ufCHf9sUi4f73Kpw      # this comes from http://gitlab/admin/runners and
                                                  # has to be hardcoded. shouldn't change often however
  volumes:
    - /usr/bin/docker:/usr/bin/docker             # so our scripts can call on docker to do things if we need them to
    - /var/run/docker.sock:/var/run/docker.sock   # this will allow the runner to spawn new docker-based runners
    - ${HOST_RNR_CONFIG_PATH}:/etc/gitlab-runner
